export { default as Lobby } from 'containers/Lobby'
export { default as Login } from 'containers/Login'
export { default as Room } from 'containers/Room'
export { default as Howmany } from 'containers/Howmany'
export { default as NoMatch } from 'containers/NoMatch'